package ir.amv.os.mps.tfp.dao.api;

/*Generated by MPS */

import ir.amv.os.vaseline.data.apis.dao.basic.server.crud.IBaseCrudDao;

import ir.amv.os.mps.tfp.model.api.IMyModelModel;
public interface IMyModelDao extends IBaseCrudDao<IMyModelModel, Long> {
}
