package ir.amv.os.mps.tfp.business.api;

/*Generated by MPS */

import ir.amv.os.vaseline.business.apis.basic.layer.server.crud.IBaseCrudApi;

import ir.amv.os.mps.tfp.model.api.IMyModelModel;
public interface IMyModelBusiness extends IBaseCrudApi<IMyModelModel, Long> {
}
