package ir.amv.os.mps.tfp.dao.impl.spring;

/*Generated by MPS */

import org.springframework.stereotype.Repository;
import ir.amv.os.vaseline.data.spring.jpa.server.crud.BaseSpringJpaCrudDaoImpl;
import ir.amv.os.vaseline.data.jpa.apis.dao.server.crud.IBaseImplementedJpaCrudDao;

import ir.amv.os.mps.tfp.dao.api.IMyModelDao;
import ir.amv.os.mps.tfp.model.api.IMyModelModel;
import ir.amv.os.mps.tfp.model.impl.jpa.MyModelJpaModelImpl;
@Repository
public class MyModelSpringDaoImpl extends BaseSpringJpaCrudDaoImpl<IMyModelModel, Long> implements IMyModelDao, IBaseImplementedJpaCrudDao<IMyModelModel, Long> {
  public Class<? extends IMyModelModel> getEntityClass() {
    return MyModelJpaModelImpl.class;
  }
}
