package ir.amv.os.mps.tfp.rest.api;

/*Generated by MPS */

import ir.amv.os.vaseline.ws.rest.apis.basic.layer.crud.IBaseCrudRestService;

import ir.amv.os.mps.tfp.model.dto.MyModelDto;

import javax.ws.rs.Path;

@Path("/myModel")
public interface IMyModelRest extends IBaseCrudRestService<MyModelDto, Long> {

}
