package ir.amv.os.mps.tfp.model.api;

/*Generated by MPS */

import ir.amv.os.vaseline.basics.apis.core.server.base.entity.IBaseEntity;

public interface IMyModelModel extends IBaseEntity<Long> {
  String getFirstName();
  IMyModelModel getRel();
  void setFirstName(String firstName);
  void setRel(IMyModelModel rel);
}
