package ir.amv.os.mps.tfp.service.api;

/*Generated by MPS */

import ir.amv.os.vaseline.service.apis.basic.layer.server.crud.IBaseCrudService;

import ir.amv.os.mps.tfp.model.dto.MyModelDto;
public interface IMyModelService extends IBaseCrudService<MyModelDto, Long> {
}
