package ir.amv.os.mps.tfp.service.impl.spring;

/*Generated by MPS */

import org.springframework.stereotype.Component;
import ir.amv.os.vaseline.service.apis.basic.layerimpl.server.crud.IBaseImplementedCrudService;
import javax.validation.Validator;
import ir.amv.os.vaseline.basics.apis.core.server.base.exc.handler.ICoreExceptionHandler;
import ir.amv.os.vaseline.basics.apis.mapper.server.objmapper.IVaselineObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;

import ir.amv.os.mps.tfp.business.api.IMyModelBusiness;
import ir.amv.os.mps.tfp.model.api.IMyModelModel;
import ir.amv.os.mps.tfp.service.api.IMyModelService;
import ir.amv.os.mps.tfp.model.dto.MyModelDto;
@Component
public class MyModelSpringServiceImpl implements IMyModelService, IBaseImplementedCrudService<IMyModelModel, MyModelDto, Long, IMyModelBusiness> {
  private IMyModelBusiness api;
  private Validator validator;
  private ICoreExceptionHandler coreExceptionHandler;
  private IVaselineObjectMapper mapper;

  public IMyModelBusiness getApi() {
    return api;
  }

  @Override
  public Class<IMyModelModel> getEntityClass() {
    return (Class<IMyModelModel>) api.getEntityClass();
  }

  public Validator getValidator() {
    return validator;
  }
  public ICoreExceptionHandler getCoreExceptionHandler() {
    return coreExceptionHandler;
  }
  public IVaselineObjectMapper getMapper() {
    return mapper;
  }

  @Autowired
  public void setApi(IMyModelBusiness api1) {
    api = api1;
  }

  @Autowired
  public void setValidator(Validator validator) {
    this.validator = validator;
  }
  @Autowired
  public void setCoreExceptionHandler(ICoreExceptionHandler coreExceptionHandler) {
    this.coreExceptionHandler = coreExceptionHandler;
  }
  @Autowired
  public void setMapper(IVaselineObjectMapper mapper) {
    this.mapper = mapper;
  }
}
