package ir.amv.os.mps.tfp.model.impl.jpa;

/*Generated by MPS */

import ir.amv.os.mps.tfp.model.api.IMyModelModel;
import ir.amv.os.vaseline.basics.apis.dao.server.ent.BaseEntityImpl;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
@Entity
public class MyModelJpaModelImpl extends BaseEntityImpl<Long> implements IMyModelModel {
  private String firstName;
  private IMyModelModel rel;
  public String getFirstName() {
    return firstName;
  }
  @ManyToOne(fetch = FetchType.LAZY, targetEntity = MyModelJpaModelImpl.class)
  public IMyModelModel getRel() {
    return rel;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }
  public void setRel(IMyModelModel rel) {
    this.rel = rel;
  }

}
