package ir.amv.os.mps.tfp.model.dto;

/*Generated by MPS */

import ir.amv.os.vaseline.basics.apis.core.shared.base.dto.base.baseimpl.BaseDtoImpl;

public class MyModelDto extends BaseDtoImpl<Long> {
  private String firstName;
  private MyModelDto rel;
  public String getFirstName() {
    return firstName;
  }
  public MyModelDto getRel() {
    return rel;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }
  public void setRel(MyModelDto rel) {
    this.rel = rel;
  }
}
