package ir.amv.os.mps.tfp.rest.impl.spring;

/*Generated by MPS */

import ir.amv.os.mps.tfp.model.dto.MyModelDto;
import ir.amv.os.mps.tfp.rest.api.IMyModelRest;
import ir.amv.os.mps.tfp.service.api.IMyModelService;
import ir.amv.os.vaseline.ws.rest.apis.basic.layerimpl.crud.IBaseImplementedCrudRestService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class MyModelSpringRestImpl implements IMyModelRest, IBaseImplementedCrudRestService<MyModelDto, Long, IMyModelService> {
  private IMyModelService service;

  public IMyModelService getService() {
    return service;
  }

  @Autowired
  public void setService(IMyModelService service1) {
    service = service1;
  }

}
