package ir.amv.os.mps.tfp.business.impl.spring;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import ir.amv.os.vaseline.basics.apis.core.server.proxyaware.defimpl.ProxyAwareImpl;
import ir.amv.os.vaseline.business.apis.basic.layerimpl.server.crud.IBaseImplementedCrudApi;
import ir.amv.os.vaseline.business.apis.basic.layer.server.action.executor.IVaselineBusinessActionExecutor;
import org.springframework.beans.factory.annotation.Autowired;

import ir.amv.os.mps.tfp.business.api.IMyModelBusiness;
import ir.amv.os.mps.tfp.dao.api.IMyModelDao;
import ir.amv.os.mps.tfp.model.api.IMyModelModel;
@Service
public class MyModelSpringBusinessImpl extends ProxyAwareImpl implements IMyModelBusiness, IBaseImplementedCrudApi<IMyModelModel, Long, IMyModelDao> {
  private IMyModelDao dao;
  private IVaselineBusinessActionExecutor businessActionExecutor;

  public IMyModelDao getDao() {
    return dao;
  }

  public IVaselineBusinessActionExecutor getBusinessActionExecutor() {
    return businessActionExecutor;
  }
  @Autowired
  public void setDao(IMyModelDao dao) {
    this.dao = dao;
  }
  @Autowired
  public void setBusinessActionExecutor(IVaselineBusinessActionExecutor businessActionExecutor) {
    this.businessActionExecutor = businessActionExecutor;
  }
}
